import { sample } from '../src';

describe('StringSampler', () => {
  [
    {
      input: {
        type: 'string',
        format: 'email'
      },
      expected: 'jon.snow@targaryen.com'
    },
    {
      input: {
        type: 'string',
        format: 'idn-email'
      },
      expected: 'джон.сноу@таргариен.укр'
    },
    {
      input: {
        type: 'string',
        format: 'pattern',
        pattern: '\\d{1,3}'
      },
      expected: '44'
    },
    {
      input: {
        type: 'string',
        format: 'password',
        minLength: 25
      },
      expected: 'p@$$w0rdp@$$w0rdp@$$w0rdp'
    },
    {
      input: {
        type: 'string',
        format: 'password',
        maxLength: 4
      },
      expected: 'p@$$'
    },
    {
      input: {
        type: 'string',
        format: 'binary'
      },
      expected: '\x01\x02\x03\x04\x05'
    },
    {
      input: {
        type: 'string',
        format: 'dummy'
      },
      expected: 'lorem'
    },
    {
      input: {
        type: 'string',
        format: 'date-time'
      },
      expected: '2021-12-31T23:34:00Z'
    },
    {
      input: {
        type: 'string',
        format: 'time'
      },
      expected: '23:34:00Z'
    },
    {
      input: {
        type: 'string',
        format: 'duration'
      },
      expected: 'P3D'
    },
    {
      input: {
        type: 'string',
        format: 'ipv4',
        maxLength: 100
      },
      expected: '208.67.222.222'
    },
    {
      input: {
        type: 'string',
        format: 'ipv6',
        minLength: 39
      },
      expected: '0000:0000:0000:0000:0000:ffff:d043:dcdc'
    },
    {
      input: {
        type: 'string',
        format: 'hostname',
        minLength: 1
      },
      expected: 'brokencrystals.com'
    },
    {
      input: {
        type: 'string',
        format: 'idn-hostname'
      },
      expected: 'сломанные-кристаллы.бел'
    },
    {
      input: {
        type: 'string',
        format: 'uri'
      },
      expected: 'https://github.com/NeuraLegion/brokencrystals'
    },
    {
      input: {
        type: 'string',
        format: 'uri-reference'
      },
      expected: '../brokencrystals'
    },
    {
      input: {
        type: 'string',
        format: 'uri-template'
      },
      expected: 'https://brokencrystals.com/api/file/{provider}'
    },
    {
      input: {
        type: 'string',
        format: 'iri'
      },
      expected:
        'https://be.wikipedia.org/wiki/%D0%9A%D1%80%D1%8B%D1%88%D1%82%D0%B0%D0%BB%D1%96'
    },
    {
      input: {
        type: 'string',
        format: 'iri-reference'
      },
      expected: '/wiki/%D0%9A%D1%80%D1%8B%D1%88%D1%82%D0%B0%D0%BB%D1%96'
    },
    {
      input: {
        type: 'string',
        format: 'json-pointer'
      },
      expected: '/json/pointer'
    },
    {
      input: {
        type: 'string',
        format: 'relative-json-pointer'
      },
      expected: '1/relative/json/pointer'
    },
    {
      input: {
        type: 'string',
        format: 'regex'
      },
      expected: '/regex/'
    },
    {
      input: {
        type: 'string',
        format: 'byte',
        minLength: 1,
        maxLength: 100
      },
      expected: 'ZHVtbXkgYmluYXJ5IHNhbXBsZQA='
    },
    {
      input: {
        type: 'string',
        format: 'base64',
        minLength: 28
      },
      expected: 'ZHVtbXkgYmluYXJ5IHNhbXBsZQA='
    },
    {
      input: {
        type: 'string',
        format: 'uuid',
        minLength: 1,
        maxLength: 36
      },
      expected: 'fbdf5a53-161e-4460-98ad-0e39408d8689'
    }
  ].forEach(({ input, expected }) => {
    const { type, format, ...restrictions } = input;
    const suffixStr = Object.keys(restrictions).length
      ? ` with restrictions ${JSON.stringify(restrictions)}`
      : '';
    it(`should sample \`${format}\` format string${suffixStr}`, () => {
      const result = sample(input);

      expect(result).toEqual(expected);
    });
  });

  [
    {
      input: {
        type: 'string',
        maxLength: 5,
        minLength: 10
      },
      expected:
        'Sample string cannot be generated by boundaries: minLength=10, maxLength=5, format=default'
    },
    {
      input: {
        type: 'string',
        format: 'pattern',
        pattern: '\\d{10,20}',
        maxLength: 5
      },
      expected:
        'Sample string cannot be generated by boundaries: maxLength=5, format=pattern'
    },
    {
      input: {
        type: 'string',
        format: 'date',
        minLength: 11
      },
      expected:
        'Sample string cannot be generated by boundaries: minLength=11, format=date'
    },
    {
      input: {
        type: 'string',
        format: 'date',
        minLength: 1,
        maxLength: 9
      },
      expected:
        'Sample string cannot be generated by boundaries: minLength=1, maxLength=9, format=date'
    },
    {
      input: {
        type: 'string',
        format: 'uuid',
        maxLength: 35
      },
      expected:
        'Sample string cannot be generated by boundaries: maxLength=35, format=uuid'
    }
  ].forEach(({ input, expected }) => {
    const { type, ...restrictions } = input;
    it(`should throw an error on controversial constrains ${JSON.stringify(
      restrictions
    )}`, () => {
      const result = () => sample(input);

      expect(result).toThrowError(expected);
    });
  });
});
