name: CI / Automated testing

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx lerna bootstrap --hoist
      - run: npx lerna run format
      - run: npx lerna run lint
      - run: npx lerna run build
      - run: npx lerna run test
